### ISSUE TITLE
Hook configuration via Spring Bean

### ISSUE THREAD

**Issue by Numichi** [Numichi/reactive-logger#12]
With keep old `Configuration.addHook` and `Configuration.addGeneticHook` methods.

**Comment by Numichi** [comment]
Support like:

```kotlin
// Ofc, similar in Java

@Configuration
class MDCHookConfiguration {

    @Bean
    fun hook1() = MDCHook<String>("hook1", "", 100) { _, _ -> mapOf() }

    @Bean
    @ConditionalOnClass(TraceContext::class)
    fun hook2() = MDCHook<TraceContext>(MDC::class.simpleName, TraceContext::class.java) { traceContext, _ ->
        mapOf(
            "traceId" to (traceContext?.traceId() ?: ""),
            "parentId" to (traceContext?.parentId() ?: ""),
            "spanId" to (traceContext?.spanId() ?: "")
        )
    }
}
```

```yml
// application.properties/yml configuration
reactive-logger:
  default:
    key: "defaultKey"
    scheduler: parallel
```
